import scala.util.Try
import scala.util.control.Exception._


// TODO -me-  use allCatch and nonFatalCatch with opt
//            use "42".toInt and "abc".toInt
val opt1:Option[Int] = ???
val opt2:Option[Int] = ???


// TODO -me-  use allCatch with withTry
//            use "42".toInt and "abc".toInt
val try1:Try[Int] = ???
val try2:Try[Int] = ???
