import scala.util.Try
import scala.util.control.Exception._


// TODO -me- use allCatch and nonFatalCatch with opt
val opt1:Option[Int] = ???
val opt2:Option[Int] = ???


// TODO -me- use allCatch with withTry
val try1:Try[Int] = ???
val try2:Try[Int] = ???
