<html>
<head>
<title>d_controlException_all.sc</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.ln { color: rgb(0,0,0); font-weight: normal; font-style: normal; }
.s0 { color: rgb(0,0,128); font-weight: bold; }
.s1 { }
.s2 { color: rgb(48,128,96); font-style: italic; }
.s3 { color: rgb(128,128,128); font-style: italic; }
.s4 { }
.s5 { color: rgb(0,128,0); font-weight: bold; }
.s6 { color: rgb(0,0,255); }
.s7 { color: rgb(190,105,50); }
</style>
</head>
<BODY BGCOLOR="#ffffff">
<TABLE CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#C0C0C0" >
<TR><TD><CENTER>
<FONT FACE="Arial, Helvetica" COLOR="#000000">
d_controlException_all.sc</FONT>
</center></TD></TR></TABLE>
<pre>

<a name="l1"><span class="ln">1    </span></a><span class="s0">import </span><span class="s1">java.util.NoSuchElementException 
<a name="l2"><span class="ln">2    </span></a> 
<a name="l3"><span class="ln">3    </span></a></span><span class="s0">import </span><span class="s1">scala.util.Try 
<a name="l4"><span class="ln">4    </span></a></span><span class="s0">import </span><span class="s1">scala.util.control.Exception._ 
<a name="l5"><span class="ln">5    </span></a></span><span class="s0">import </span><span class="s1">scala.util.control.NonFatal 
<a name="l6"><span class="ln">6    </span></a> 
<a name="l7"><span class="ln">7    </span></a></span><span class="s2">// ====================================</span><span class="s1"> 
<a name="l8"><span class="ln">8    </span></a></span><span class="s2">// -1- INTRO</span><span class="s1"> 
<a name="l9"><span class="ln">9    </span></a></span><span class="s2">// ====================================</span><span class="s1"> 
<a name="l10"><span class="ln">10   </span></a></span><span class="s2">//</span><span class="s1"> 
<a name="l11"><span class="ln">11   </span></a></span><span class="s3">/** 
<a name="l12"><span class="ln">12   </span></a> * compose exception handlers 
<a name="l13"><span class="ln">13   </span></a> * 
<a name="l14"><span class="ln">14   </span></a> * Scala Documentation - scala.util.control.Exception 
<a name="l15"><span class="ln">15   </span></a> * =================== 
<a name="l16"><span class="ln">16   </span></a> * This class differs from </span><span class="s4">`</span><span class="s3">scala.util.Try</span><span class="s4">` </span><span class="s3">in that it focuses on 
<a name="l17"><span class="ln">17   </span></a> * composing exception handlers rather than composing behavior. 
<a name="l18"><span class="ln">18   </span></a> */</span><span class="s1"> 
<a name="l19"><span class="ln">19   </span></a></span><span class="s3">/** TODO -me-  usage of NonFatal */</span><span class="s1"> 
<a name="l20"><span class="ln">20   </span></a></span><span class="s0">val </span><span class="s1">nonFatal: Int = </span><span class="s0">try </span><span class="s1">{ 
<a name="l21"><span class="ln">21   </span></a>  </span><span class="s5">&quot;abc&quot;</span><span class="s1">.toInt 
<a name="l22"><span class="ln">22   </span></a>} </span><span class="s0">catch </span><span class="s1">{ 
<a name="l23"><span class="ln">23   </span></a>  </span><span class="s0">case </span><span class="s1">NonFatal(e) =&gt; -</span><span class="s6">1</span><span class="s1"> 
<a name="l24"><span class="ln">24   </span></a>} 
<a name="l25"><span class="ln">25   </span></a> 
<a name="l26"><span class="ln">26   </span></a> 
<a name="l27"><span class="ln">27   </span></a></span><span class="s2">// TODO -me-  use allCatch and nonFatalCatch with</span><span class="s1"> 
<a name="l28"><span class="ln">28   </span></a></span><span class="s2">//            1) opt  and  2) withTry</span><span class="s1"> 
<a name="l29"><span class="ln">29   </span></a></span><span class="s2">//            use &quot;42&quot;.toInt and &quot;abc&quot;.toInt</span><span class="s1"> 
<a name="l30"><span class="ln">30   </span></a></span><span class="s0">val </span><span class="s1">opt1:Option[Int] = allCatch[Int].opt(</span><span class="s5">&quot;42&quot;</span><span class="s1">.toInt) 
<a name="l31"><span class="ln">31   </span></a></span><span class="s0">val </span><span class="s1">opt2:Try[Int] = nonFatalCatch[Int].withTry(</span><span class="s5">&quot;abc&quot;</span><span class="s1">.toInt) 
<a name="l32"><span class="ln">32   </span></a> 
<a name="l33"><span class="ln">33   </span></a> 
<a name="l34"><span class="ln">34   </span></a></span><span class="s2">// ==&gt; PUI legalInformation</span><span class="s1"> 
<a name="l35"><span class="ln">35   </span></a> 
<a name="l36"><span class="ln">36   </span></a> 
<a name="l37"><span class="ln">37   </span></a></span><span class="s2">//</span><span class="s1"> 
<a name="l38"><span class="ln">38   </span></a></span><span class="s2">// ====================================</span><span class="s1"> 
<a name="l39"><span class="ln">39   </span></a></span><span class="s2">// -2- Generator</span><span class="s1"> 
<a name="l40"><span class="ln">40   </span></a></span><span class="s2">// ====================================</span><span class="s1"> 
<a name="l41"><span class="ln">41   </span></a> 
<a name="l42"><span class="ln">42   </span></a></span><span class="s2">// Creates a `Catch` object which will catch any of the supplied exceptions.</span><span class="s1"> 
<a name="l43"><span class="ln">43   </span></a></span><span class="s2">// TODO -me-  lt's write an handler which catch the</span><span class="s1"> 
<a name="l44"><span class="ln">44   </span></a></span><span class="s2">//            - NumberFormatException -&gt; return 0</span><span class="s1"> 
<a name="l45"><span class="ln">45   </span></a></span><span class="s2">//              and</span><span class="s1"> 
<a name="l46"><span class="ln">46   </span></a></span><span class="s2">//            - IllegalArgumentException -&gt; return -1</span><span class="s1"> 
<a name="l47"><span class="ln">47   </span></a></span><span class="s3">/** 
<a name="l48"><span class="ln">48   </span></a> * container which catch the defined exception 
<a name="l49"><span class="ln">49   </span></a> */</span><span class="s1"> 
<a name="l50"><span class="ln">50   </span></a></span><span class="s0">val </span><span class="s1">handleIntConverting = catching[Int]( 
<a name="l51"><span class="ln">51   </span></a>    classOf[NumberFormatException]</span><span class="s7">,</span><span class="s1"> 
<a name="l52"><span class="ln">52   </span></a>    classOf[IllegalArgumentException]) 
<a name="l53"><span class="ln">53   </span></a> 
<a name="l54"><span class="ln">54   </span></a>  .withApply(e =&gt; { 
<a name="l55"><span class="ln">55   </span></a>    println(</span><span class="s5">&quot;oh. we have to fallback to default values&quot;</span><span class="s1">) 
<a name="l56"><span class="ln">56   </span></a>    e </span><span class="s0">match </span><span class="s1">{ 
<a name="l57"><span class="ln">57   </span></a>      </span><span class="s0">case </span><span class="s1">e: NumberFormatException =&gt; </span><span class="s6">0</span><span class="s1"> 
<a name="l58"><span class="ln">58   </span></a>      </span><span class="s0">case </span><span class="s1">_:Throwable =&gt; -</span><span class="s6">1</span><span class="s1"> 
<a name="l59"><span class="ln">59   </span></a>    } 
<a name="l60"><span class="ln">60   </span></a>}) 
<a name="l61"><span class="ln">61   </span></a> 
<a name="l62"><span class="ln">62   </span></a> 
<a name="l63"><span class="ln">63   </span></a></span><span class="s2">// TODO -me-  &quot;42&quot; / &quot;abc42def&quot;.toInt and use handleIntConverting</span><span class="s1"> 
<a name="l64"><span class="ln">64   </span></a></span><span class="s0">val </span><span class="s1">test1: Int = handleIntConverting.apply(</span><span class="s5">&quot;42&quot;</span><span class="s1">.toInt) 
<a name="l65"><span class="ln">65   </span></a></span><span class="s0">val </span><span class="s1">test2: Int = handleIntConverting(</span><span class="s5">&quot;abc42def&quot;</span><span class="s1">.toInt) 
<a name="l66"><span class="ln">66   </span></a>assert(test1 == </span><span class="s6">42</span><span class="s1">) 
<a name="l67"><span class="ln">67   </span></a>assert(test2 == </span><span class="s6">0</span><span class="s1">) 
<a name="l68"><span class="ln">68   </span></a> 
<a name="l69"><span class="ln">69   </span></a></span><span class="s2">//</span><span class="s1"> 
<a name="l70"><span class="ln">70   </span></a></span><span class="s2">// TODO -2-  use handleIntConverting and throw an IllegalArgumentException</span><span class="s1"> 
<a name="l71"><span class="ln">71   </span></a></span><span class="s2">//           write the assert statement before you implement</span><span class="s1"> 
<a name="l72"><span class="ln">72   </span></a></span><span class="s0">val </span><span class="s1">test3: Int = handleIntConverting {</span><span class="s0">throw new </span><span class="s1">IllegalArgumentException} 
<a name="l73"><span class="ln">73   </span></a>assert(test3 == -</span><span class="s6">1</span><span class="s1">) 
<a name="l74"><span class="ln">74   </span></a> 
<a name="l75"><span class="ln">75   </span></a> 
<a name="l76"><span class="ln">76   </span></a></span><span class="s2">//</span><span class="s1"> 
<a name="l77"><span class="ln">77   </span></a></span><span class="s2">// ====================================</span><span class="s1"> 
<a name="l78"><span class="ln">78   </span></a></span><span class="s2">// -3- Handling</span><span class="s1"> 
<a name="l79"><span class="ln">79   </span></a></span><span class="s2">// ====================================</span><span class="s1"> 
<a name="l80"><span class="ln">80   </span></a></span><span class="s2">//</span><span class="s1"> 
<a name="l81"><span class="ln">81   </span></a></span><span class="s2">// TODO -me-  short analogy to try/catch</span><span class="s1"> 
<a name="l82"><span class="ln">82   </span></a></span><span class="s0">val </span><span class="s1">test5: Int = handling[Int](classOf[NumberFormatException]) 
<a name="l83"><span class="ln">83   </span></a>  .by (_ =&gt;</span><span class="s6">1</span><span class="s1">) apply </span><span class="s5">&quot;sd&quot;</span><span class="s1">.toInt 
<a name="l84"><span class="ln">84   </span></a> 
<a name="l85"><span class="ln">85   </span></a></span><span class="s2">// TODO -1-  can u identify the analogy?</span><span class="s1"> 
<a name="l86"><span class="ln">86   </span></a></span><span class="s0">val </span><span class="s1">test6: Int = </span><span class="s0">try </span><span class="s1">{ 
<a name="l87"><span class="ln">87   </span></a>  </span><span class="s5">&quot;sb&quot;</span><span class="s1">.toInt 
<a name="l88"><span class="ln">88   </span></a>} 
<a name="l89"><span class="ln">89   </span></a></span><span class="s0">catch </span><span class="s1">{ 
<a name="l90"><span class="ln">90   </span></a>  </span><span class="s0">case </span><span class="s1">_: NumberFormatException =&gt; </span><span class="s6">1</span><span class="s1"> 
<a name="l91"><span class="ln">91   </span></a>} 
<a name="l92"><span class="ln">92   </span></a> 
<a name="l93"><span class="ln">93   </span></a>assert(test5 == test6)</span></pre>
</body>
</html>